[build]
target = "index.html"
dist = "dist"

[build.watch]
watch = ["src", "assets"]

[[build.copy]]
source = "assets"
target = "assets"

[build.copy-wasm]
manifest = false
lock = false
features = []
